meta:
  url: https://neotheicebird.github.io/how-to-build-modern-web-apps
  title: How to build Modern Web Apps
  description: A Talk about crafting web application in modern times. The intention is to help beginners choose a good set of tools and become aware of the "services" model of building apps.
  siteName: https://neotheicebird.github.io
  sns: ['twitter']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: progressbar # bullets | progressbar | fraction
    effect: fade # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: dark # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
